[package]
name = "pwninit"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]
edition = "2018"
description = "automate starting binary exploit challenges"
repository = "https://github.com/io12/pwninit"
readme = "README.md"
keywords = ["pwn", "init", "binary", "elf", "exploit", "pwntools", "cli"]
license = "MIT"

[dependencies]
twoway = "0.2.1"
structopt = "0.3.3"
goblin = "0.0.24"
reqwest = "0.9.22"
ar = "0.8.0"
tar = "0.4.26"
rust-lzma = "0.4.0"
umask = "0.1.6"
is_executable = "0.1.2"
tempdir = "0.3.7"
colored = "1.8.0"
